from telebot import types
from telebot.util import per_thread

adm = types.ReplyKeyboardMarkup(True)
adm.add("Запустить рассылку🔈", "Добавить промокод🎟")
adm.add("Удалить промокод🎟","Добавить админа👨‍💻")
adm.add("Меню🧞‍♀️")


menu = types.ReplyKeyboardMarkup(True)
menu.add("🌆Выбрать город", "🎫Промокод")
menu.add("👨‍💻Оператор")

pay_menu = types.ReplyKeyboardMarkup(True)
pay_menu.add("Я оплатил✅","Меню🧞‍♀️")


city = types.InlineKeyboardMarkup()
btn1 = types.InlineKeyboardButton("💠Нур-Султан", callback_data="ast")
btn2 = types.InlineKeyboardButton("💠Кульсары", callback_data="kul")
btn3 = types.InlineKeyboardButton("💠Актау", callback_data="akt")
btn4 = types.InlineKeyboardButton("💠Актобе", callback_data="aktb")
btn5 = types.InlineKeyboardButton("💠Алматы", callback_data="alm")
btn6 = types.InlineKeyboardButton("💠Атырау", callback_data="atr")
btn7 = types.InlineKeyboardButton("💠Капшагай", callback_data="kap")
btn8 = types.InlineKeyboardButton("💠Караганда", callback_data="kar")
btn9 = types.InlineKeyboardButton("💠Каскелен", callback_data="kask")
btn10 = types.InlineKeyboardButton("💠Кокшетау", callback_data="koksh")
btn11 = types.InlineKeyboardButton("💠Кызылорда", callback_data="kuz")
btn12 = types.InlineKeyboardButton("💠Павлодар", callback_data="pavl")
btn13 = types.InlineKeyboardButton("💠Петропавловск", callback_data="petr")
btn14 = types.InlineKeyboardButton("💠Сарань", callback_data="saran")
btn15 = types.InlineKeyboardButton("💠Семей", callback_data="sem")
btn16 = types.InlineKeyboardButton("💠Талдыкорган", callback_data="tald")
btn17 = types.InlineKeyboardButton("💠Тараз", callback_data="taraz")
btn18 = types.InlineKeyboardButton("💠Темиртау", callback_data="tem")
btn19 = types.InlineKeyboardButton("💠Туркестан", callback_data="tyrk")
btn20 = types.InlineKeyboardButton("💠Уральск", callback_data="uralsk")
btn21 = types.InlineKeyboardButton("💠Усть-Каменогорск", callback_data="ustkam")
btn22 = types.InlineKeyboardButton("💠Шахтинск", callback_data="shaht")
btn23 = types.InlineKeyboardButton("💠Шымкент", callback_data="shum")
btn24 = types.InlineKeyboardButton("💠Экибастуз", callback_data="ekuba")
delete = types.InlineKeyboardButton("❌Закрыть",callback_data="delete")
city.row(btn1, btn2)
city.row(btn3, btn4)
city.row(btn5, btn6)
city.row(btn7, btn8)
city.row(btn9, btn10)
city.row(btn11, btn12)
city.row(btn13, btn14)
city.row(btn15, btn16)
city.row(btn17, btn18)
city.row(btn19, btn20)
city.row(btn21, btn22)
city.row(btn23, btn24)
city.row(delete)
cancel = types.InlineKeyboardMarkup()
cancel.row(delete)

spam = types.InlineKeyboardMarkup()
spam_text = types.InlineKeyboardButton("💬Спам текстом💬", callback_data="text")
spam_pic = types.InlineKeyboardButton("🖼Спам с картинкой🖼", callback_data="pics")
cancel_spam = types.InlineKeyboardButton("🙅Отмена рассылки🙅", callback_data="stop_spam")
spam.row(spam_text, spam_pic)
spam.row(cancel_spam)

staff = types.InlineKeyboardMarkup()
stf1 = types.InlineKeyboardButton("Гаш 🍫", callback_data="Гаш 🍫")
stf2 = types.InlineKeyboardButton("Ск синий 🔵", callback_data="Ск синий 🔵")
stf3 = types.InlineKeyboardButton("Ск красный 🔴", callback_data="Ск красный 🔴")
stf4 = types.InlineKeyboardButton("Бошки White Widow 🌳", callback_data="Бошки White Widow 🌳")
stf5 = types.InlineKeyboardButton("Бошки АК-47 🌿", callback_data="Бошки АК-47 🌿")
stf6 = types.InlineKeyboardButton("Бошки Critical Kush 🌲", callback_data="Бошки Critical Kush 🌲")
stf7 = types.InlineKeyboardButton("Амф ⚡️", callback_data="Амф ⚡️")
stf8 = types.InlineKeyboardButton("Героин🍚", callback_data="Героин🍚")
stf9 = types.InlineKeyboardButton("План/Трим 🍃", callback_data="План/Трим 🍃")
stf10 = types.InlineKeyboardButton("Меф ❄️", callback_data="Меф ❄️")
stf11 = types.InlineKeyboardButton("Лирика 300 💊", callback_data="Лирика 300 💊")
back_city = types.InlineKeyboardButton("Вернуться к выбору города🌇", callback_data="back_city")
staff.row(stf1)
staff.row(stf2)
staff.row(stf3)
staff.row(stf4)
staff.row(stf5)
staff.row(stf6)
staff.row(stf7)
staff.row(stf8)
staff.row(stf9)
staff.row(stf10)
staff.row(stf11)
staff.row(back_city)

back_city = types.InlineKeyboardButton("Вернуться к выбору товара📦", callback_data="back_tovar")
gash = types.InlineKeyboardMarkup()
g1 = types.InlineKeyboardButton("1г – 13 500 ₸", callback_data="1г – 13500 ₸")
g2 = types.InlineKeyboardButton("2г – 24 500 ₸", callback_data="2г – 24500 ₸")
g3 = types.InlineKeyboardButton("3г – 34 500 ₸", callback_data="3г – 34500 ₸")
gash.row(g1)
gash.row(g2)
gash.row(g3)
gash.row(back_city)

sk_bl = types.InlineKeyboardMarkup()
sk_bl1 = types.InlineKeyboardButton("1г – 13 000 ₸", callback_data="1г – 13000 ₸")
sk_bl2 = types.InlineKeyboardButton("2г – 22 000 ₸", callback_data="2г – 22000 ₸")
sk_bl3 = types.InlineKeyboardButton("3г – 33 000 ₸", callback_data="3г – 33000 ₸")
sk_bl.row(sk_bl1)
sk_bl.row(sk_bl2)
sk_bl.row(sk_bl3)
sk_bl.row(back_city)

sk_rd = types.InlineKeyboardMarkup()
sk_rd1 = types.InlineKeyboardButton("1г – 14 000 ₸", callback_data="1г – 14000 ₸")
sk_rd2 = types.InlineKeyboardButton("2г – 23 000 ₸", callback_data="2г – 23000 ₸")
sk_rd3 = types.InlineKeyboardButton("3г – 34 000 ₸", callback_data="3г – 34000 ₸")
sk_rd.row(sk_rd1)
sk_rd.row(sk_rd2)
sk_rd.row(sk_rd3)
sk_rd.row(back_city)

ww = types.InlineKeyboardMarkup()
ww1 = types.InlineKeyboardButton("1г – 14 000 ₸", callback_data="1г – 14000 ₸")
ww2 = types.InlineKeyboardButton("2г – 24 000 ₸", callback_data="2г – 24000 ₸")
ww3 = types.InlineKeyboardButton("3г – 35 000 ₸", callback_data="3г – 35000 ₸")
ww.row(ww1)
ww.row(ww2)
ww.row(ww3)
ww.row(back_city)

ak = types.InlineKeyboardMarkup()
ak1 = types.InlineKeyboardButton("1г – 12 000 ₸", callback_data="1г – 12000 ₸")
ak2 = types.InlineKeyboardButton("2г -  21 000 ₸", callback_data="2г - 21000 ₸")
ak3 = types.InlineKeyboardButton("3г – 30 000 ₸", callback_data="3г – 30000 ₸")
ak.row(ak1)
ak.row(ak2)
ak.row(ak3)
ak.row(back_city)

kush = types.InlineKeyboardMarkup()
kush1 = types.InlineKeyboardButton("1г – 13 500 ₸", callback_data="1г – 13500 ₸")
kush2 = types.InlineKeyboardButton("2г – 24 500 ₸", callback_data="2г – 24500 ₸")
kush3 = types.InlineKeyboardButton("3г – 34 500 ₸", callback_data="3г – 34500 ₸")
kush.row(kush1)
kush.row(kush2)
kush.row(kush3)
kush.row(back_city)

mef = types.InlineKeyboardMarkup()
mef1 = types.InlineKeyboardButton("1г – 13 000 ₸", callback_data="1г – 13000 ₸")
mef2 = types.InlineKeyboardButton("2г – 22 000 ₸", callback_data="2г – 22000 ₸")
mef3 = types.InlineKeyboardButton("3г – 33 000 ₸", callback_data="3г – 33000 ₸")
mef.row(mef1)
mef.row(mef2)
mef.row(mef3)
mef.row(back_city)

amf = types.InlineKeyboardMarkup()
amf1 = types.InlineKeyboardButton("1г – 11 500 ₸", callback_data="1г – 11500 ₸")
amf2 = types.InlineKeyboardButton("2г – 20 500 ₸", callback_data="2г – 20500 ₸")
amf3 = types.InlineKeyboardButton("3г – 31 500 ₸", callback_data="3г – 31500 ₸")
amf.row(amf1)
amf.row(amf2)
amf.row(amf3)

ger = types.InlineKeyboardMarkup()
ger1 = types.InlineKeyboardButton("1г – 15 000 ₸", callback_data="1г – 15000 ₸")
ger2 = types.InlineKeyboardButton("2г – 26 000 ₸", callback_data="2г – 26000 ₸")
ger3 = types.InlineKeyboardButton("3г – 39 000 ₸", callback_data="3г – 39000 ₸")
ger.row(ger1)
ger.row(ger2)
ger.row(ger3)
ger.row(back_city)

plan = types.InlineKeyboardMarkup()
plan1 = types.InlineKeyboardButton("2г – 12 000 ₸", callback_data="2г – 12000 ₸")
plan2 = types.InlineKeyboardButton("4г – 21 000 ₸", callback_data="4г – 21000 ₸")
plan.row(plan1)
plan.row(plan2)
plan.row(back_city)

lira = types.InlineKeyboardMarkup()
lira1 = types.InlineKeyboardButton("5шт - 10 000 ₸", callback_data="5шт – 10000 ₸")
lira2 = types.InlineKeyboardButton("7шт - 12 000 ₸", callback_data="7шт – 12000 ₸")
lira3 = types.InlineKeyboardButton("14шт - 20 000 ₸", callback_data="14шт – 20000 ₸")
lira.row(lira1)
lira.row(lira2)
lira.row(lira3)
lira.row(back_city)


mef = types.InlineKeyboardMarkup()
mef1 = types.InlineKeyboardButton("1г – 13 000 ₸", callback_data="1г – 13000 ₸")
mef2 = types.InlineKeyboardButton("2г – 22 000 ₸", callback_data="2г – 22000 ₸")
mef3 = types.InlineKeyboardButton("3г – 33 000 ₸", callback_data="3г – 33000 ₸")
mef.row(mef1)
mef.row(mef2)
mef.row(mef3)
mef.row(back_city)

cancel_order = types.InlineKeyboardMarkup()
cancel_order.row(types.InlineKeyboardButton("🙅‍♂️Отменить заказ🙅‍♂️", callback_data="cancel_order"))







